Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,28 +29,37 @@ jobs:
       - name: Install Dependencies
         run: flutter pub get
 
-      - name: Run DCL
-        run: dcl analyze --reporter=github lib
+      - name: Ensure dart_code_linter is in dev_dependencies
+        run: |
+          dart pub remove dart_code_linter || true
+          dart pub add --dev dart_code_linter
 
-      #- name: Run dart_code_linter
-      #  id: dart_code_linter
-      #  run: dart run dart_code_linter:metrics analyze . --reporter=html --output-directory=./html_reports
-      #  continue-on-error: false  # Stop build if linting fails
+      - name: Run DCL
+        id: dart_code_linter
+        run: dart run dart_code_linter:metrics analyze . --reporter=html --output-directory=./html_reports
+        continue-on-error: false  # Stop build if linting fails
 
       - name: Install lcov
         run: brew install lcov
 
       - name: Run Tests
         id: test
-        #if: success()  # Run only if linting passes
-        run: flutter test --coverage
+        run: flutter test --coverage || true  # Continue even if tests fail
 
       - name: Generate Coverage Report
-        #if: success()  # Generate only if tests pass
         run: |
           genhtml coverage/lcov.info --output-directory=coverage/lcov-report
 
-  build_and_upload_on_success:
+      - name: Install Allure CLI
+        run: brew install allure
+
+      - name: Run tests and generate Allure report
+        run: |
+          set -o pipefail
+          dart run test_reporter -- flutter test
+          allure generate allure-results --single-file -o allure-report --clean
+
+  build_and_upload_artifact_on_success:
     name: Build & Upload Artifacts (Success)
     runs-on: macos-latest
     needs: build
@@ -80,41 +89,49 @@ jobs:
           cd build
           tar -czf ios_build.tar.gz ios
 
-      - name: Generate Artifact Version
-        id: version
-        run: echo "VERSION=$(git rev-parse --short HEAD)-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
-
-      - name: Upload Build Artifacts and Coverage Report
+      - name: Upload Build Artifacts, Coverage Report, and Allure Report
         uses: actions/upload-artifact@v4
         with:
-          name: Build-and-Coverage-${{ env.VERSION }}
+          name: Build-and-Coverage-and-Allure
           path: |
             build/app/outputs/flutter-apk/app-debug.apk
             build/app/outputs/bundle/debug/app-debug.aab
             build/ios_build.tar.gz
             coverage/lcov-report
+            allure-report
 
-  upload_build_and_coverage:
+  upload_build_and_coverage_in_google_drive_on_success:
     name: Upload Build and Coverage to Google Drive
     runs-on: ubuntu-latest
-    needs: build_and_upload_on_success
+    needs: build_and_upload_artifact_on_success
+    if: success()
+
     steps:
       - name: Download Build Artifacts
         uses: actions/download-artifact@v4
         with:
-          name: Build-and-Coverage-${{ env.VERSION }}
+          name: Build-and-Coverage-and-Allure
           path: artifacts
+
+      - name: List artifacts folder before zipping
+        run: |
+          ls -la artifacts
+
+      - name: Create Build-and-Coverage ZIP
+        run: |
+          cd artifacts
+          zip -r Build-and-Coverage.zip .
 
       - name: Upload Build ZIP to Google Drive
         uses: adityak74/google-drive-upload-git-action@main
         with:
           credentials: ${{ secrets.CREDENTIALS }}
           folderId: ${{ secrets.FOLDERID }}
-          filename: Build-and-Coverage-${{ env.VERSION }}.zip
+          filename: artifacts/Build-and-Coverage.zip
 
   build_and_upload_on_failure:
-    name: Upload Coverage Report on Failure
-    runs-on: ubuntu-latest
+    name: Upload Coverage Report and Allure Report on Failure
+    runs-on: macos-latest
     needs: build
     if: failure()
 
@@ -122,19 +139,39 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Generate Artifact Version
-        id: version
-        run: echo "VERSION=$(git rev-parse --short HEAD)-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
-
-      - name: Upload Coverage Report as Artifact
+      - name: Upload Coverage Report and Allure Report as Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: Coverage-${{ env.VERSION }}
-          path: coverage/lcov-report
+          name: Coverage-and-Allure
+          path: |
+            coverage/lcov-report
+            allure-report
+
+  upload_coverage_in_google_drive_on_failure:
+    name: Upload Coverage in Google Drive on Failure
+    runs-on: ubuntu-latest
+    needs: build_and_upload_on_failure
+    if: failure()
+
+    steps:
+      - name: Download Coverage Report Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: Coverage-and-Allure
+          path: artifacts
+
+      - name: List artifacts folder before zipping
+        run: |
+          ls -la artifacts
+
+      - name: Create Coverage-and-Allure ZIP
+        run: |
+          cd artifacts
+          zip -r Coverage-and-Allure.zip .
 
       - name: Upload Coverage Report ZIP to Google Drive
         uses: adityak74/google-drive-upload-git-action@main
         with:
           credentials: ${{ secrets.CREDENTIALS }}
           folderId: ${{ secrets.FOLDERID }}
-          filename: Coverage-${{ env.VERSION }}.zip
+          filename: artifacts/Coverage-and-Allure.zip
