Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,8 +1,3 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
 name: Dart
 
 on:
@@ -17,48 +12,55 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-      # Note: This workflow uses the latest stable version of the Dart SDK.
-      # You can specify other versions if desired, see documentation here:
-      # https://github.com/dart-lang/setup-dart/blob/main/README.md
-      # - uses: dart-lang/setup-dart@v1
       - name: Setup Flutter SDK
         uses: flutter-actions/setup-flutter@v3
         with:
           channel: stable
 
-      - name: Install dependencies
+      - name: Install Dependencies
         run: dart pub global activate melos
 
-      - name: Melos Bootstrap
+      - name: Verify Melos Installation
+        run: melos --version
+
+      - name: Check if Melos Workspace Exists
+        run: |
+          if [ ! -f "melos.yaml" ]; then
+            echo "melos.yaml not found! Ensure you have set up Melos workspace."
+            exit 1
+          fi
+
+      - name: Bootstrap Melos
         run: melos bs
 
-      - name: Install
-        run: |
-          melos allures:install
-      - name: Generate
+      - name: Debug Melos Packages
+        run: melos list
+
+      - name: Install Allure Dependencies
+        run: melos allures:install
+
+      - name: Generate Reports
         run: melos generate
 
-      # Consider passing '--fatal-infos' for slightly stricter analysis.
-      - name: Analyze project source
+      - name: Analyze Project Source
         run: dart analyze
 
-      # Your project will need to have tests in test/ and a dependency on
-      # package:test for this step to succeed. Note that Flutter projects will
-      # want to change this to 'flutter test'.
-      - name: Run tests
+      - name: Run Tests
         continue-on-error: true
         run: melos test
 
-      - name: Aggregate results
+      - name: Aggregate Test Results
         run: |
           rm -rf allure-results
           mkdir allure-results-tmp
           find . -path "*/allure-results/*" -type f -exec cp '{}' ./allure-results-tmp/ \;
           mv allure-results-tmp allure-results
           zip -r allure-results.zip allure-results/
-      - name: Test marketplace action
+
+      - name: Generate Allure Report
         uses: simple-elf/allure-report-action@master
         if: always()
         id: allure-report
